### ISSUE TITLE
Scan is not working

### ISSUE THREAD

**Issue by Rashad-Harfani** [HybridNetworks/MimosaDiscoveryTool#1]
i have multiple mimosa c5c links , when i press scan none of them appear . is there a manual to this program ? is there any firewall changes i should do on my laptop ?

**Comment by danielcshn** [comment]
Hi, please complete the form below:

**PC IP ADDRESS RANGE:** _???.???.???.??? / ??_
**MIMOSA IP ADDRESS RANGE:** _???.???.???.??? / ??_
**MIMOSA MAC ADDRESS IS:** _20:B5:C6:??:??:??_ (yes/no)
